__descr__ = '{{cookiecutter.description}}'
__version__ = '{{cookiecutter.version}}'
__license__ = '{{cookiecutter.license}}'
__author__ = u'{{cookiecutter.author}}'
__author_short__ = u'{{cookiecutter.author_short}}'
__author_email__ = '{{cookiecutter.email}}'
__copyright__ = u'{{cookiecutter.copyright}} {{cookiecutter.author}}'
__url__ = '{{cookiecutter.url}}'
