name: style

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [checks]

    steps:
    - uses: actions/checkout@v3
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

    - name: Test with tox
      run: tox -e ${{ matrix.toxenv }}
