name: cookiecutter-tests

on: [push]

jobs:
  cookiecutter-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tools
        run: |
          pip install cookiecutter

      - name: Run Cookiecutter
        run: |
          cookiecutter --no-input https://github.com/kiwi-lang/python_seed

      - name: Install dependencies
        run: |
          cd myproject
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m venv ~/env
          source ~/env/bin/activate
          pip install tox
          make install

      - name: tests-doc
        run: |
          cd myproject
          source ~/env/bin/activate
          tox -e py
          tox -e black
          tox -e isort
          tox -e doc8
          tox -e docs
          tox -e pylint
