name: openpr

on:
  push:
  workflow_dispatch:

jobs:
  openpr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: dependencies
      run: | 
        sudo apt-get install -y git rsync jq

    - name: OpenPR
      run: |
        bash scripts/generate_cookie.sh
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
